create database olympics;
use olympics;
desc olympics;
select*from olympics;
alter table olympics
rename column name to name_;
alter table olympics
rename column sex to Gender;
select*from olympics;
ALTER TABLE OLYMPICS 
RENAME COLUMN YEAR TO YEAR_;
SELECT*FROM OLYMPICS;

#1).TO DISPLAY MINIMUM AND MAXIMUM YEAR OF OLYMPICS SPORT PRESENT IN DATASET
SELECT MIN(YEAR_) FROM OLYMPICS;
SELECT MAX(YEAR_) FROM OLYMPICS;

alter table olympics 
rename column event to event_;

#2).TO DISPLAY THE COUNT OF TOTAL PLAYERS OF OLYMPICS 
SELECT COUNT(NAME_) FROM OLYMPICS;

#3).TO DISPLAY COUNT OF FEMALES AND MALES
SELECT COUNT(GENDER) AS MALES FROM OLYMPICS WHERE GENDER = 'M';
SELECT COUNT(GENDER) AS FEMALES FROM OLYMPICS WHERE GENDER= 'F';

#4).TO FIND THE COUNT OF GOLD,SILVER AND BRONZE MEDAL 
SELECT COUNT(MEDAL) AS GOLD FROM OLYMPICS WHERE MEDAL = 'GOLD';
SELECT COUNT(MEDAL) AS SILVER FROM OLYMPICS WHERE MEDAL = 'SILVER';
SELECT COUNT(MEDAL) AS BRONZE FROM OLYMPICS WHERE MEDAL = 'BRONZE';

#5).TO DISPLAY NAME ,GENDER ,AGE ,TEAM AND SPORT OF THE PLAYER WHO HAS WON THE GOLD MEDAL
SELECT NAME_,GENDER,AGE,TEAM,SPORT FROM OLYMPICS WHERE MEDAL ='GOLD';

#6).TO DISPLAY THE COUNT OF FEMALS AND MALES OUT OF 34 GOLD MEDALIST
SELECT COUNT(MEDAL) AS MALE_WINNER FROM OLYMPICS WHERE MEDAL= 'GOLD' AND GENDER = 'M';
SELECT COUNT(MEDAL) AS FEMALE_WINNER FROM OLYMPICS WHERE MEDAL='GOLD' AND GENDER ='F';

#7). TO DISPLAY THE THE COUNT OF FEAMLES AND MALES WHO HAS WON SILVER MEDAL
SELECT COUNT(MEDAL) AS MALE_WINNER FROM OLYMPICS WHERE MEDAL= 'SILVER' AND GENDER = 'M';
SELECT COUNT(MEDAL) AS FEMALE_WINNER FROM OLYMPICS WHERE MEDAL='SILVER' AND GENDER ='F';

#8). TO DISPLAY THE THE COUNT OF FEAMLES AND MALES WHO HAS WON BRONZE MEDAL
SELECT COUNT(MEDAL) AS MALE_WINNER FROM OLYMPICS WHERE MEDAL= 'BRONZE' AND GENDER = 'M';
SELECT COUNT(MEDAL) AS FEMALE_WINNER FROM OLYMPICS WHERE MEDAL='BRONZE' AND GENDER ='F';

#9).TO DISPLAY THE NAME OF THE TOP 5 PLAYERS WHO HAS WON MOST OF THE MEDALS IN‘GOLD, SILVER, BRONZE’.
select name_,medal, count(medal) as 'COUNT' from olympics WHERE MEDAL IN ('GOLD','SILVER','BRONZE')group by  name_, medal order by COUNT desc LIMIT 5;

#10).TO DISPLAY THE NAME OF FEMALES WHO GOT GOLD MEDAL
SELECT NAME_ , sport , age FROM OLYMPICS WHERE GENDER = 'F'AND MEDAL = 'GOLD';

#11). TO DISPLAY THE DETAILS OF PLAYER WHO GOT GOLD MEDAL AND BELONGS FROM TEAM INDIA
SELECT*FROM OLYMPICS WHERE MEDAL = 'GOLD' AND TEAM = 'INDIA';

#12). TO DISPLAY THE TYPES OF SPORT IN OLYMPICS
SELECT DISTINCT SPORT FROM OLYMPICS; #(USED DISTINCT FUNCTION BECAUSE THERE IS SAME SPORT HAS PLAYED FOR DIFFERENT EVENT) 
SELECT COUNT(SPORT) FROM OLYMPICS;

#13).TO DISPLAY THE NAME OF TOP 5 SPORT WHICH HAS WON MAX MEDALS IN ' GOLD,SILVER AND BRONZE'
SELECT SPORT, MEDAL , COUNT(MEDAL) AS COUNT FROM OLYMPICS WHERE MEDAL IN ('GOLD','SILVER','BRONZE') GROUP BY SPORT,MEDAL ORDER BY COUNT DESC LIMIT 5; 

#14). TO FIND CANADIAN WHO HAS WON THE GOLD MEDAL
SELECT NAME_ , GENDER FROM OLYMPICS WHERE TEAM ='CANADA'AND MEDAL ='GOLD';
 
 #15).TO FIND THE NAME OF FEMALE WHO HAS WON MEDALS IN GOLD ,SILVER AND BRONZE
SELECT NAME_,AGE,SPORT,TEAM,MEDAL FROM OLYMPICS WHERE GENDER ='F' AND MEDAL IN ('GOLD','SILVER','BRONZE');
Select count(NAME_) from olympics where gender ='f' and medal in ('gold','silver','bronze');

#16).TO FIND THE FEMALES WHO HASN'T WON ANY MEDAL IN GOLD ,SILVER AND BRONZE
SELECT NAME_ ,AGE,SPORT,TEAM,MEDAL FROM OLYMPICS WHERE GENDER ='F' AND MEDAL not in ('GOLD','SILVER','BRONZE') ;
select count(NAME_) from olympics where gender ='f' and medal not in ('gold','silver','bronze');

#17). TO FIND THE NAME ,AGE , SPORT AND YEAR OF SILVER AND BRONZE MEDAL WINNER PLAYER AND SHOW COUNT OF THE MEDAL 
SELECT NAME_ , AGE , SPORT , YEAR_  AS SILVER_WINNER FROM OLYMPICS WHERE MEDAL='SILVER';
SELECT COUNT(name_)FROM OLYMPICS WHERE MEDAL= 'SILVER';
SELECT NAME_ , AGE , SPORT , YEAR_  AS BRONZE_WINNER FROM OLYMPICS WHERE MEDAL ='BRONZE';
SELECT COUNT(NAME_) AS BRONZE FROM OLYMPICS WHERE MEDAL= 'BRONZE';

#18).TO DISPLAY THE DETAILS OF PLAYER WHO'S AGE IS < 30 AND BELONGS TO TEAM 'NORWAY' AND HAS WON 'GOLD' MEDAL
SELECT*FROM OLYMPICS WHERE AGE < 30 AND TEAM = 'NORWAY' AND MEDAL = 'GOLD';

#19).TO DISPLAY THE DETAILS OF THE PLAYER WHO HAD PLAYED AN OLYMPICS BETWEEN YEAR 2000 TO 2010 AND WON SILVER MEDAL 
SELECT*FROM OLYMPICS WHERE YEAR_ BETWEEN 2000 AND 2010 AND  MEDAL = 'SILVER';

#20).TO DISPLAY THE DETAILS OF THE PLAYER WHO HAS WON SILVER MEDAL BETWEEN 1995 TO 2000 IN SUMMER SEASON IN WRESTLING 
SELECT*FROM OLYMPICS WHERE YEAR_ BETWEEN 1995 AND 2000 AND SEASON LIKE 'SUMMER' AND SPORT LIKE'WRESTLING' AND MEDAL LIKE 'SILVER';

# 21).Display the first name and team for all player whose first name starts with an p
select  name_,team,age from olympics where name_ like "P%";

#22).Display the first name and sport for all player whose first name ends with an e
select name_,sport from olympics where name_ like "%e";

#23).Display the team and  for all player whose team contin  an s
select team from olympics where team like "%s%";

#24).TO DISPLAY MR. AND MRS. AS PER GENDER
SELECT IF(gender = 'M', LPAD(NAME_ ,LENGTH(NAME_)+3 ,'MR '), LPAD(NAME_ ,LENGTH(NAME_)+ 4 ,'MRS ' )) FROM OLYMPICS;

#25). Display the name concatenated with the SPORT, separated by comma, and MEDAL, for all  PLAYERS whose YEAR not in the range between 2003-2014.
#Sort the query in ascending order by the full name 
SELECT CONCAT(NAME_,'-',SPORT,'-',MEDAL) FROM OLYMPICS WHERE YEAR_ NOT BETWEEN 2005 AND 2010 ORDER BY NAME_ ;

#26).TO CHECK IF DUBLICATE EXIST OR NOT 
SELECT name_, age, sport, year_,event_,season,height,weight,gender,  COUNT(*) as appearance_count FROM olympics GROUP BY name_, age, sport, year_,event_,season,
height,weight,gender;

#27). TO DISPLAY THE TOP 5 AGE GROUP WHICH HAS WON MOST OF THE MEDALS
SELECT AGE,MEDAL, MAX(AGE) AS MAX , COUNT(MEDAL) AS COUNT FROM OLYMPICS WHERE MEDAL IN ('GOLD','SILVER','BRONZE') GROUP BY AGE,MEDAL ORDER BY COUNT DESC LIMIT 5;


#28) TO DISPLAY THE RECORDS OF THE PLAYER WHO PLAYED MORE THAN ONE IN SAME YEAR ,AGE AND SPORT BUT FOR DIFFERNT EVENT
SELECT name_, age, sport, year_, COUNT(*) as count FROM olympics GROUP BY name_, age, sport, year_ HAVING  COUNT >1;

SELECT COUNT(DISTINCT SPORT) FROM OLYMPICS;

#29).TO DISPLAY TOP 5 SPORTS WHICH HAVE BEEN ORGANISED MOST OF THE TIME IN OLYMPICS
SELECT SPORT, COUNT(SPORT) AS COUNT FROM OLYMPICS GROUP BY SPORT ORDER BY COUNT DESC LIMIT 5;

#30).SELECT AGE, COUNT(AGE) AS COUNT FROM OLYMPICS WHERE YEAR_ BETWEEN 1995 AND 2016 GROUP BY AGE ORDER BY COUNT DESC;
SELECT NAME_ FROM OLYMPICS WHERE SPORT = 'ATHLETICS' OR AGE BETWEEN 16 AND 35;

# 31).string functions replace "winter" season with "winter_season" from the table
select replace (Season,"Winter","Winter_games")from olympics;

#32).
Alter table olympics;
Select weight from olympics where ID = 562;

#33).Display medal ascending & Descending order by and having limit 3,1 & 4,2 respectvely.
Select team,medal from olympics order by medal asc limit 5,3;
Select team medal from olympics order by medal desc limit 4,2;

#34).Display name column with upper cammand
select upper(name_) from olympics;
 
#35).Display name column with lower cammand
select lower(name_) from olympics;

#36).DISPLAY ID,NAME,TEAM AND AGE IS NOT EQUAL TO 20,25,30.(OLYMPIC TABLE) BY USING IN.
SELECT ID,NAME_,TEAM,AGE FROM OLYMPICS WHERE AGE NOT IN (20,25,30);

#37).
select avg(age) from olympics;
select name_,age from olympics where age <25;
select name_,age from olympics where age >40;
select name_,age from olympics where age <>20;
select name_,team,age from olympics where age between 25 and 40;

#38)
SELECT YEAR_ FROM OLYMPICS ORDER BY YEAR_;

#39).DISPLAY THE ALL DATA FROM OLYMPICS TABLE FOR ALL SPORTS PERSONS WHOSE PARTICIPATED 
#IN BETWEEN 1920 TO 2016 AND WON "BRONZE" MEDAL . 
SELECT NAME_,TEAM,GENDER,AGE,SPORT,YEAR_,MEDAL FROM OLYMPICS 
WHERE YEAR_ > 1920 AND YEAR_ < 2016 AND MEDAL ='BRONZE';

#40)DISPLAY THE SILVER AND BRONZE MEDAL WINNER COUNT
SELECT MEDAL,COUNT(*)AS MEDALCOUNT FROM OLYMPICS WHERE MEDAL IN ('GOLD','SILVER'AND'BRONZE') GROUP BY MEDAL;

#41).
SELECT NAME_,TEAM,GENDER,
COUNT(MEDAL ="SILVER")  AS SILVERCOUNT,
count(MEDAL ="BRONZE") AS BRONZECOUNT
FROM OLYMPICS GROUP BY NAME_,TEAM,GENDER;

#42).DISPLAY ALL INFORMATION ABPUT SPORTS PERSON WHO PLAY BASKETBALL IN OLYMPICS
SELECT * FROM OLYMPICS WHERE EVENT LIKE "BASKETBALL MENS'S BASKETBALL";

#43).DISPLAY UNIQUE EVENT FROM TABLE.
SELECT distinct (EVENT) FROM OLYMPICS;

#44).DISPLAY NAME & TEAM TOGETHER BY USING COCAT
select concat(NAME_, '        ' ,TEAM)  from olympics;
SELECT * FROM OLYMPICS;

#45).DISPLAY THE COUNT OF SPORTS PERSON WHO PARTICIPATED IN SUMMER OLYMPICS.
SELECT COUNT(GENDER)FROM OLYMPICS WHERE GENDER = "M" AND SEASON ="SUMMER";
SELECT COUNT(GENDER)FROM OLYMPICS WHERE GENDER = "F" AND SEASON ="SUMMER";

#46).DISPLAY THE COUNT OF SPORTS PERSON WHO PARTICIPATED IN WINTER OLYMPICS.
SELECT COUNT(GENDER)FROM OLYMPICS WHERE GENDER = "M" AND SEASON ="WINTER";
SELECT COUNT(GENDER)FROM OLYMPICS WHERE GENDER = "F" AND SEASON ="WINTER";

